//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewPreference
    {
        public int Id { get; set; }
        public int PCMId { get; set; }
        public int SubmissionId { get; set; }
    
        public virtual Submission Submission { get; set; }
        public virtual User User { get; set; }
    }
}
